name: Test and build

on:
  push:
    tags:
      - v[0-9]+.*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Tidy and test
      run: |
        set -e

        for dir in src/*; do
          if [ -f "$dir/go.mod" ]; then
            echo "Running go mod tidy in $dir"
            (cd "$dir" && go mod tidy)

            echo "Running tests in $dir"
            (cd "$dir" && go test ./...)
          fi
        done

    - name: Run build
      run: |
        go run tools/build-tool.go
